### PR TITLE
Fix phone number input validation 

### LINKED ISSUE #62: Add Form Validation for phoneNumber

### PR DESCRIPTION
**Pull request by Quinn-H**
close #62

### CODE REVIEW

File: src/client/components/Join/Join.js [hunk 1]
```diff
@@ -84,7 +86,7 @@ const Join = React.createClass({
             show='touched'
             messages={{
               required: 'Required',
-              maxLength: ' Must be 15 characters or less'
+              isNumber: 'Must be a phont Number'
```
Comment (amandahogan) [inline src/client/components/Join/Join.js]: spelling error "phone"

File: src/client/components/Join/__tests__/__snapshots__/Join.js.snap [hunk 2]
```diff
@@ -91,7 +92,7 @@ exports[`test Join renders correctly 1`] = `
       className="errors"
       messages={
         Object {
-          "maxLength": " Must be 15 characters or less",
+          "isNumber": "Must be a phont Number",
```
Comment (amandahogan) [inline src/client/components/Join/__tests__/__snapshots__/Join.js.snap]: Same thing "phone" and lowercase the Number: number

File: src/client/components/Join/Join.js (hunk 1 above)
Comment (amandahogan) [reply src/client/components/Join/Join.js]: lowercase the Number: number

File: src/client/components/Join/Join.js [hunk 3]
```diff
@@ -3,6 +3,7 @@ import { Control, Errors, Form } from 'react-redux-form'
 
 const required = val => val && val.length
 const maxLength = length => val => val && val.length <= length
+const isNumber = val => !isNaN(Number(val))
```
Comment (amandahogan) [inline src/client/components/Join/Join.js]: Don't worry about this too much ... but we could alphabetize const? Ask David :P

**Review by amandahogan — CHANGES_REQUESTED** [review]
Minor changes
